// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nredhhslnwxgfkabtaqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yZWRoaHNsbnd4Z2ZrYWJ0YXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTQ4NzAsImV4cCI6MjA3Mzg3MDg3MH0.B_F6TreC-glF3ShyuXECEv7O0whDRCcdFZH7PkKfe6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});